### ISSUE TITLE
Unable to run on flutter

### ISSUE THREAD

**Issue by SweetSourPeter** [AhmedKhattab95/qr_code_sample#1]
Hey Ahamed, I tried to run your app but it seems like taking forever to run Gradle task 'assembleDebug'... Have you ever encountered the same problem? Thanks

**Comment by AhmedKhattab95** [comment]
Gradle may take some minutes to run and it depends on internet speed,
I cloned the app in a new folder and works fine on this version of flutter and dart
```
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 2.8.4
```
you can run ` flutter --version` to see the installed version
and also can run `flutter update` to update to latest version
